"""Baseline validation — JSONL-backed store for classification ground truth.

Two samples managed in parallel:
- "classified" : files that Klodo did classify; user confirms or corrects
- "atrier"     : files Klodo dumped to _A-TRIER; user provides correct folder

Records live as JSONL in profiles/<profile>/.cache/, generated by
scripts/build_validation_sample.py and scripts/build_atrier_sample.py.
"""

from __future__ import annotations

import json
import threading
from datetime import datetime
from pathlib import Path

from dashboard import data

# In-memory state (mode, profile) → list[dict]
_records_cache: dict[tuple[str, str], list[dict]] = {}
_lock = threading.Lock()


def _sample_path(profile: str, mode: str) -> Path:
    """Return the JSONL path for a (profile, mode) pair."""
    repo_root = data.get_project_root()
    cache_dir = repo_root / "profiles" / profile / ".cache"
    if mode == "classified":
        return cache_dir / "validation_sample.jsonl"
    if mode == "atrier":
        return cache_dir / "validation_atrier_sample.jsonl"
    raise ValueError(f"Unknown mode: {mode!r} (expected 'classified' or 'atrier')")


def _load(profile: str, mode: str, force_reload: bool = False) -> list[dict]:
    """Load JSONL records into memory, with caching."""
    key = (profile, mode)
    with _lock:
        if not force_reload and key in _records_cache:
            return _records_cache[key]

        path = _sample_path(profile, mode)
        if not path.exists():
            _records_cache[key] = []
            return []

        records: list[dict] = []
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))
        _records_cache[key] = records
        return records


def _save(profile: str, mode: str, records: list[dict]) -> None:
    """Atomically rewrite the JSONL file."""
    path = _sample_path(profile, mode)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".jsonl.tmp")
    with tmp.open("w") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    tmp.replace(path)


def stats(profile: str, mode: str) -> dict:
    """Return progression stats for a (profile, mode) pair."""
    records = _load(profile, mode)
    total = len(records)
    validated = sum(1 for r in records if r.get("verdict"))
    if mode == "classified":
        correct = sum(1 for r in records if r.get("verdict") == "correct")
        wrong = sum(1 for r in records if r.get("verdict") == "wrong")
        skip = sum(1 for r in records if r.get("verdict") == "skip")
        return {
            "total": total, "validated": validated, "remaining": total - validated,
            "correct": correct, "wrong": wrong, "skip": skip,
            "exists": total > 0,
        }
    # atrier mode
    classified = sum(1 for r in records if r.get("verdict") == "classified")
    skip = sum(1 for r in records if r.get("verdict") == "skip")
    return {
        "total": total, "validated": validated, "remaining": total - validated,
        "classified": classified, "skip": skip,
        "exists": total > 0,
    }


def next_record(profile: str, mode: str) -> dict | None:
    """Return the next unvalidated record, or None if all done."""
    records = _load(profile, mode)
    for r in records:
        if not r.get("verdict"):
            return r
    return None


def get_record(profile: str, mode: str, file_id: str) -> dict | None:
    """Look up a record by file_id."""
    records = _load(profile, mode)
    for r in records:
        if r.get("file_id") == file_id:
            return r
    return None


def save_verdict(
    profile: str,
    mode: str,
    file_id: str,
    verdict: str,
    ground_truth: str | None = None,
    notes: str | None = None,
) -> bool:
    """Update a record's verdict. Returns False if file_id not found."""
    valid_classified = {"correct", "wrong", "skip"}
    valid_atrier = {"classified", "skip"}
    valid = valid_classified if mode == "classified" else valid_atrier
    if verdict not in valid:
        raise ValueError(f"Invalid verdict {verdict!r} for mode {mode!r}")

    records = _load(profile, mode)
    found = False
    for r in records:
        if r.get("file_id") == file_id:
            r["verdict"] = verdict
            r["validated_at"] = datetime.now().isoformat(timespec="seconds")
            if ground_truth is not None:
                r["ground_truth"] = ground_truth
            elif verdict == "correct":
                # Confirm the predicted folder as ground truth
                r["ground_truth"] = r.get("predicted_folder")
            if notes is not None:
                r["notes"] = notes
            found = True
            break

    if found:
        _save(profile, mode, records)
        # Invalidate cache to ensure consistency
        with _lock:
            _records_cache.pop((profile, mode), None)
    return found


def reset_cache() -> None:
    """Clear in-memory cache (useful when JSONL is regenerated)."""
    with _lock:
        _records_cache.clear()


def list_target_folders(profile: str) -> list[str]:
    """Return the list of valid folder paths for ground-truth selection.

    Reads from tree.yaml of the given profile.
    """
    repo_root = data.get_project_root()
    tree_path = repo_root / "profiles" / profile / "tree.yaml"
    if not tree_path.exists():
        return []
    import yaml
    tree = yaml.safe_load(tree_path.read_text())
    return sorted(
        f for f in tree.get("folders", [])
        if not f.startswith("_")
    )


def resolve_source_path(profile: str, rel_path: str) -> Path | None:
    """Resolve a relative path to its absolute location on disk.

    Returns None if the file does not exist.
    """
    import yaml
    repo_root = data.get_project_root()
    profile_path = repo_root / "profiles" / profile / "profile.yaml"
    if not profile_path.exists():
        return None
    cfg = yaml.safe_load(profile_path.read_text())
    target = Path(cfg.get("target") or cfg.get("target_path") or "")
    candidate = target / rel_path
    return candidate if candidate.exists() else None


def baseline_thumbnail_dir(profile: str, file_id: str) -> Path:
    """Return the cache dir for a file_id's thumbnail (not under .thumbnail-cache).

    Stored under .baseline-thumbs/ to avoid colliding with the Curation cache.
    """
    repo_root = data.get_project_root()
    cache = repo_root / "profiles" / profile / ".cache" / ".baseline-thumbs" / file_id
    return cache
